#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )


# Set the list of directories that Zsh searches for programs.
# Also the PKGCONFIG path and possibly other environment variables.
# host dependent
case $HOST in
  (ESLT*)
    path=(
      /Users/pbos/sw/miniconda3/bin
      /opt/local/{bin,sbin}
      /usr/local/{bin,sbin}
      /Users/pbos/.gem/ruby/2.3.0/bin
      /Users/pbos/sw/bin
      $path
    )
    export PKG_CONFIG_PATH=$HOME/sw/lib/pkgconfig
    export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
    export GEM_HOME=$HOME/.gem/ruby/2.3.0/gems
  ;;
  (flappi.local)
    path=(
      /opt/local/{bin,sbin}
      $path
    )
  ;;
  (mlp*)
    path=(
      $HOME/sw/bin
      $HOME/sw/miniconda2/bin
      $path
    )
  ;;
  (*)
    path=(
      $HOME/miniconda2/bin
      $HOME/sw/bin
      /usr/local/{bin,sbin}
      $path
    )
  ;;
esac

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

