#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases
alias rm='nocorrect rm -I'

# turn off noclobber
setopt clobber

# lsetup stuff on stoomboot
source /project/atlas/nikhef/cvmfs/setup.sh
setupATLAS

# git
lsetup git
