#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# added by Miniconda2 4.0.5 installer (in .bashrc, niet hier, zelf gedaan!)
export PATH="/home/patrick/miniconda2/bin:$PATH"
