#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# for powerlevel9k theme
# some things, like the _MODE variable, need to be set before loading the theme through prezto!
export DEFAULT_USER=pbos

export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context ssh dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time)

export POWERLEVEL9K_MODE='nerdfont-complete'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases
#alias rm='nocorrect rm -I'
alias rm='nocorrect rm'

# turn off noclobber
setopt clobber

# added by Miniconda3 4.3.11 installer
# (in .bash_profile, moved here by me)
#export PATH="/Users/pbos/sw/miniconda3/bin:$PATH"
# moved paths to zprofile path list!

# macports
#export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# host dependent things
case $HOST in
  (ESLT0072)
    # ROOT loading
    alias apcocsm_root_debug='source /Users/pbos/projects/apcocsm/root-roofit-dev/cmake-build-debug/bin/thisroot.sh'
  ;;
  (stbc-i*)
    # lsetup stuff on interactive stoomboot nodes
    source /project/atlas/nikhef/cvmfs/setup.sh
    setupATLAS
    # git
    lsetup git
  ;;
  (*)
    echo "How did I get in the middle of nowhere?"
    echo $HOST
  ;;
esac


